"use strict";
/* a class to provide methods to work with PC & NPC
*/
export class Character {
    static defaultData() {
        return({
        name: '',
        location : "Home",
        inv: [],  //inventory data, needs to be mapped to Inventory-Instance
        wardrobe: [],  //separate wardobe data, needs to be mapped to outfit-Instance
        outfit: [],  // needs to be mapped to outfit-Instance
        stats: [],
        effects: [],
        rel: [],
        money : 0,
        });
    }
    constructor(externlist) {
        this._data = externlist ? externlist : Character.defaultData();
        this.Outfit = new Outfit(this,this._data.outfit);
        this.Inv = new Inventory(this,this._data.inv);
        this.Wardrobe = new Inventory(this,this._data.wardrobe);
        this.Stats = new Stats(this,this._data.stats);
        this.Effects = new Effects(this,this._data.effects);
        this.Rel = new Stats(this,this._data.rel); //Todo Relation similiar to stats?
        //create basic stats
        var _i = this.Stats.findItemSlot('health');
        if(_i<0) this.Stats.list.push({id: 'health', min: 0, max: 60 , value: 50});
        _i = this.Stats.findItemSlot('energy');
        if(_i<0) this.Stats.list.push({id: 'energy', min: 0, max: 100 , value: 80});
    }

    health() {
        var val = this.Stats.get('health');
        return(val);
    }
    energy() {
        var val = this.Stats.get('energy');
        return(val);
    }

    gainStat(id,val) {
        var _x = this.Stats.get(id);
        var old = _x.value; 
        var _new = Math.max(_x.min,Math.min(_x.max,old+val));
        _x.value = _new;
        if(_new-old>=0) {
            window.gm.pushLog('<statup>'+id+" regenerated by "+(_new-old).toString()+"</statup></br>");
        } else {
            window.gm.pushLog('<statdown>'+id+" decreased by "+(_new-old).toString()+"</statdown></br>");
        }
    }

    gainRelation(char,val) {
        this.Rel.addItem(char)
        var _x = this.Rel.get(char);
        var old = _x.value; 
        var _new = Math.max(_x.min,Math.min(_x.max,old+val));
        _x.value = _new;
        var diff = _new-old;
        if(diff>0) {
            window.gm.pushLog('<statup>Your relation to '+char+" improved by "+diff.toString()+"</statup></br>");
        } else if (diff<0) {
            window.gm.pushLog('<statdown>Your relation to '+char+" worsend by "+diff.toString()+"</statdown></br>");
        } else {
            window.gm.pushLog('Your relation to '+char+" wasnt affected at all by your behaviour.</br>");
        }
    }
}